### ISSUE TITLE
installation fails with fish

### ISSUE THREAD

**Issue by toogy** [yyuu/pyenv-virtualenvwrapper#27]
I'm trying to set up pyenv-virtualenvwrapper.

I cloned the plugin in my `~/.pyenv/plugins` directory and now I'm trying to install it (as described in this repo's readme).

Running `pyenv virtualenvwrapper` gives me the following:
```
~ λ pyenv virtualenvwrapper
pyenv-virtualenvwrapper: no such directory: 
pyenv-virtualenvwrapper: failed to initialize virtualenvwrapper.
fish: Unknown command 'unset'
/tmp/.psub.8HAtUzthcV (line 1): unset PYENV_VIRTUALENVWRAPPER_PYENV_VERSION
                                ^
from sourcing file /tmp/.psub.8HAtUzthcV
	called on line 151 of file /usr/share/fish/config.fish

in function “.”
	called on line 11 of file /tmp/.psub.VWXTxXwj2J

in function “pyenv”
	called on standard input
	with parameter list “virtualenvwrapper”
```

```
~ λ fish --version
fish, version 2.2.0
~ λ uname -a
Linux stewie 4.3.3-2-ARCH #1 SMP PREEMPT Wed Dec 23 20:09:18 CET 2015 x86_64 GNU/Linux
```

Side-note: I have **pyenv-virtualenv** installed.

**Comment by yyuu** [comment]
virtualenvwrapper doesn't support fish. Use pyenv-virtualenv to manage virtualenvs in pyenv if you're using fish.

**Comment by toogy** [comment]
Are you planning on supporting fish someday?

**Comment by yyuu** [comment]
It is an issue of virtualenvwrapper itself. Ask them if they have any plan.
