### ISSUE TITLE
通过 pyenv virtualwrapper 创建的 virtualenv， pip 版本总是过低？

### ISSUE THREAD

**Issue by pythonee** [yyuu/pyenv-virtualenvwrapper#30]
系统:os ei capitan 
系统原本的 python 版本为 python 2.7.5 ，通过 brew install python 升级到 python 2.7.11 
然后通过 pyenv 安装 python 3.5.0 

系统中就存在2.7 和 3.5两个python版本， 刚开始分别对应的 pip 版本分别为 pip 8.1.0 和 pip 8.0.2，后面我都升级了pip到8.1.0 

现在的问题是，每次通过 mkvirtualenv 来创建 virtualenv 的时候， pip --version 总是 7.1.2 ，不知道这个 pip 的版本是从哪里复制过来的，如果这样，每次创建的 virtualenv 总是要先升级 pip，为什么不能直接使用对应的python版本的pip呢？这个7.1.2的版本是从哪里过来的呢?

这是virtualenv里的pip脚本
`# -*- coding: utf-8 -*-
import re
import sys

from pip import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())`

**Comment by yyuu** [comment]
Use English
